
import React from 'react';
import { ResearchReport, UnifiedGraph, GraphNode } from '../types';

interface ReportPanelProps {
  graphData: UnifiedGraph;
  onNodeClick: (node: GraphNode) => void;
}

const ReportPanel: React.FC<ReportPanelProps> = ({ graphData, onNodeClick }) => {
  const { report } = graphData;

  if (!report) {
    return (
      <div className="flex-1 flex items-center justify-center text-gray-400">
        <p>No report generated.</p>
      </div>
    );
  }

  const findNode = (id: string) => graphData.nodes.find(n => n.id === id);

  return (
    <div className="flex-1 bg-white/5 backdrop-blur-xl h-full overflow-y-auto custom-scrollbar p-8 max-w-4xl mx-auto text-gray-100">
      <div className="mb-8 border-b border-white/10 pb-6">
        <h1 className="text-3xl font-serif text-white font-bold mb-2">Strategic Research Report</h1>
        <p className="text-gray-400 text-sm">Generated by Agent R • NexusGraph AI</p>
      </div>

      {/* Overview */}
      <section className="mb-10">
        <h2 className="text-lg font-bold text-gray-100 mb-3 border-l-4 border-cyan-500 pl-3">Executive Overview</h2>
        <p className="text-gray-200 leading-relaxed whitespace-pre-line">{report.themeOverview}</p>
      </section>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-10">
        {/* Key Players */}
        <section>
          <h2 className="text-lg font-bold text-gray-100 mb-4 border-l-4 border-emerald-500 pl-3">Critical Players</h2>
          <div className="space-y-4">
            {report.keyPlayers.map((item, idx) => {
              const node = findNode(item.nodeId);
              return (
                <div key={idx} className="bg-emerald-500/10 p-4 rounded-lg border border-emerald-400/40 hover:shadow-md transition-shadow cursor-pointer" onClick={() => node && onNodeClick(node)}>
                  <div className="font-bold text-emerald-100 mb-1">{node?.name || item.nodeId}</div>
                  <p className="text-sm text-emerald-200">{item.rationale}</p>
                </div>
              );
            })}
          </div>
        </section>

        {/* Second Tier / Hidden Gems */}
        <section>
          <h2 className="text-lg font-bold text-gray-100 mb-4 border-l-4 border-violet-500 pl-3">Hidden Opportunities</h2>
          <div className="space-y-4">
            {report.secondTierBeneficiaries.map((item, idx) => {
              const node = findNode(item.nodeId);
              return (
                <div key={idx} className="bg-violet-500/10 p-4 rounded-lg border border-violet-400/40 hover:shadow-md transition-shadow cursor-pointer" onClick={() => node && onNodeClick(node)}>
                  <div className="font-bold text-violet-100 mb-1">{node?.name || item.nodeId}</div>
                  <p className="text-sm text-violet-200">{item.rationale}</p>
                </div>
              );
            })}
          </div>
        </section>
      </div>

      {/* Risks */}
      <section className="mb-10">
        <h2 className="text-lg font-bold text-gray-100 mb-4 border-l-4 border-red-500 pl-3">Risk Assessment</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {report.riskNodes.map((item, idx) => {
                const node = findNode(item.nodeId);
                return (
                    <div key={idx} className="flex items-start gap-3 p-3 rounded-lg bg-red-500/10 border border-red-400/40">
                        <span className="text-red-300 font-bold mt-1">⚠️</span>
                        <div>
                             <div className="font-bold text-red-100 text-sm mb-0.5 cursor-pointer hover:underline" onClick={() => node && onNodeClick(node)}>
                                {node?.name || item.nodeId}
                             </div>
                             <p className="text-xs text-red-200">{item.riskFactor}</p>
                        </div>
                    </div>
                )
            })}
        </div>
      </section>

      {/* Next Steps */}
      <section className="mb-12 bg-white/5 p-6 rounded-xl border border-white/10">
        <h2 className="text-lg font-bold text-gray-100 mb-4">Recommended Actions</h2>
        <ul className="space-y-2">
            {report.suggestedNextSteps.map((step, idx) => (
                <li key={idx} className="flex items-start gap-2 text-sm text-gray-200">
                    <span className="text-cyan-400 font-bold">•</span>
                    {step}
                </li>
            ))}
        </ul>
      </section>

      {/* Disclaimer */}
      <footer className="text-xs text-gray-400 text-center border-t border-white/10 pt-6">
        <p className="font-bold mb-1">DISCLAIMER</p>
        <p>{report.disclaimer}</p>
      </footer>
    </div>
  );
};

export default ReportPanel;
